// localStorage.clear();

const EMPLOYEES = [
  {
    Id: 1,
    firstname: "Aarav",
    email: "e@e.com",
    password: "123",
    taskNumbers: { active: 2, newTask: 2, completed: 3, failed: 1 },
    tasks: [
      {
        title: "Prepare Sales Report",
        description: "Compile monthly sales report for review",
        date: "2025-08-15",
        category: "Reporting",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Client Follow-up",
        description: "Call client for project update",
        date: "2025-08-16",
        category: "Communication",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Fix Bug in Module",
        description: "Resolve login authentication bug",
        date: "2025-08-17",
        category: "Development",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Team Meeting",
        description: "Discuss upcoming project milestones",
        date: "2025-08-18",
        category: "Management",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Draft Documentation",
        description: "Update API documentation",
        date: "2025-08-19",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Missed Deadline Task",
        description: "Task not completed on time",
        date: "2025-08-10",
        category: "General",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Create Wireframes",
        description: "Prepare wireframes for new UI",
        date: "2025-08-20",
        category: "Design",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    Id: 2,
    firstname: "Ishita",
    email: "employee2@example.com",
    password: "123",
    taskNumbers: { active: 1, newTask: 2, completed: 3, failed: 0 },
    tasks: [
      {
        title: "Database Backup",
        description: "Perform weekly DB backup",
        date: "2025-08-14",
        category: "Database",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "UI Testing",
        description: "Test new UI components",
        date: "2025-08-16",
        category: "Testing",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Project Proposal Draft",
        description: "Create proposal for new client project",
        date: "2025-08-17",
        category: "Planning",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "System Update",
        description: "Update system dependencies",
        date: "2025-08-18",
        category: "Maintenance",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Employee Onboarding",
        description: "Guide new employees with system setup",
        date: "2025-08-19",
        category: "HR",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Bug Fixing",
        description: "Resolve frontend CSS issues",
        date: "2025-08-20",
        category: "Development",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    Id: 3,
    firstname: "Kabir",
    email: "employee3@example.com",
    password: "123",
    taskNumbers: { active: 2, newTask: 1, completed: 2, failed: 1 },
    tasks: [
      {
        title: "Design Logo",
        description: "Create logo for new product",
        date: "2025-08-12",
        category: "Design",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Client Presentation",
        description: "Prepare presentation for client meeting",
        date: "2025-08-15",
        category: "Communication",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Code Review",
        description: "Review teammate’s code",
        date: "2025-08-17",
        category: "Development",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Missed Task",
        description: "Task delayed beyond deadline",
        date: "2025-08-11",
        category: "General",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Deploy App",
        description: "Deploy new app version to production",
        date: "2025-08-19",
        category: "Deployment",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    Id: 4,
    firstname: "Meera",
    email: "employee4@example.com",
    password: "123",
    taskNumbers: { active: 1, newTask: 3, completed: 2, failed: 0 },
    tasks: [
      {
        title: "Content Writing",
        description: "Write blog post for company website",
        date: "2025-08-14",
        category: "Content",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Data Cleaning",
        description: "Clean and validate user data",
        date: "2025-08-15",
        category: "Data",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "SEO Optimization",
        description: "Improve website SEO ranking",
        date: "2025-08-16",
        category: "Marketing",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Team Feedback",
        description: "Collect team feedback for sprint review",
        date: "2025-08-17",
        category: "Management",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Plan Social Media Posts",
        description: "Schedule next week’s posts",
        date: "2025-08-18",
        category: "Marketing",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Bug Verification",
        description: "Verify fixed bugs before release",
        date: "2025-08-19",
        category: "Testing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    Id: 5,
    firstname: "Rohan",
    email: "employee5@example.com",
    password: "123",
    taskNumbers: { active: 2, newTask: 1, completed: 2, failed: 1 },
    tasks: [
      {
        title: "Network Setup",
        description: "Set up new office WiFi routers",
        date: "2025-08-12",
        category: "IT Support",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "System Testing",
        description: "Perform regression tests",
        date: "2025-08-14",
        category: "Testing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Documentation Update",
        description: "Update internal knowledge base",
        date: "2025-08-15",
        category: "Documentation",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Missed Task",
        description: "Incomplete due to lack of resources",
        date: "2025-08-10",
        category: "General",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Server Monitoring",
        description: "Monitor server load during peak hours",
        date: "2025-08-19",
        category: "IT Support",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Patch Update",
        description: "Apply latest security patches",
        date: "2025-08-20",
        category: "Maintenance",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
];

const ADMIN = [
  {
    Id: 101,
    email: "admin@me.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("EMPLOYEES", JSON.stringify(EMPLOYEES));
  localStorage.setItem("ADMIN", JSON.stringify(ADMIN));
};

export const getLocalStorage = () => {
  const EMPLOYEES = JSON.parse(localStorage.getItem("EMPLOYEES"));
  const ADMIN = JSON.parse(localStorage.getItem("ADMIN"));

  return { EMPLOYEES, ADMIN };
};
